import os
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

from app.core.database import get_db
from app.core.security import get_current_officer
from app.core.config import settings
from app.models.user import Officer
from app.models.report import Report
from app.models.case import Case

router = APIRouter(prefix="/reports", tags=["reports"])


class ReportGenerateRequest(BaseModel):
    report_type: str  # "Daily", "Weekly", "Case Summary"
    case_id: int | None = None  # optional case ID for case summary


def get_reports_llm():
    lc_key = settings.LANGCHAIN_API_KEY_FIR or settings.LANGCHAIN_API_KEY
    if lc_key:
        os.environ["LANGCHAIN_API_KEY"] = lc_key
        os.environ["LANGCHAIN_TRACING_V2"] = "true"
    else:
        os.environ["LANGCHAIN_TRACING_V2"] = "false"
    return ChatGroq(
        api_key=settings.GROQ_API_KEY_FIR or settings.GROQ_API_KEY,
        model=settings.GROQ_MODEL,
        temperature=0.2,
    )


REPORT_SYSTEM_PROMPT = """You are an expert police inspector writing formal reports.
Based on the provided case data, generate a highly professional and structured report (e.g. Daily Activity Report, Weekly Crime Analytics, or Case Summary Report).
The report should include sections like:
1. Executive Summary
2. Key Incident Breakdown
3. Priority Actions & Immediate Investigations
4. Signature / Sign-off Block

Format the report using clean, official, and professional language with Markdown structure.
"""


@router.get("/")
def list_reports(
    db: Session = Depends(get_db),
    _officer: Officer = Depends(get_current_officer),
):
    """Returns a list of historically generated reports."""
    reports = db.query(Report).order_by(Report.report_date.desc()).limit(100).all()
    return reports


@router.post("/generate")
def generate_report(
    payload: ReportGenerateRequest,
    db: Session = Depends(get_db),
    officer: Officer = Depends(get_current_officer),
):
    """Generates an official police report summarizing crime data or case details via AI."""
    # 1. Fetch relevant cases based on report type
    cases_covered = 0
    context_cases = []

    if payload.report_type == "Case Summary":
        if not payload.case_id:
            raise HTTPException(status_code=400, detail="case_id is required for Case Summary reports.")
        c = db.query(Case).filter(Case.id == payload.case_id).first()
        if not c:
            raise HTTPException(status_code=404, detail="Case not found.")
        context_cases.append(c)
        cases_covered = 1
    else:
        # Fetch up to 10 recent cases
        recent_cases = db.query(Case).order_by(Case.created_at.desc()).limit(10).all()
        context_cases.extend(recent_cases)
        cases_covered = len(recent_cases)

    # 2. Construct prompt context
    case_lines = []
    for c in context_cases:
        case_lines.append(
            f"- FIR: {c.fir_number or 'N/A'} | Category: {c.crime_type} | Location: {c.location} | Date: {c.incident_date} | Status: {c.status}\n  Details: {c.description}"
        )
    case_context = "\n".join(case_lines)

    prompt = f"Generate a '{payload.report_type}' report based on the following case data:\n\n{case_context}\n\nGenerated by: {officer.full_name} ({officer.badge_number})\nDate: {datetime.now().strftime('%Y-%m-%d')}"

    messages = [
        SystemMessage(content=REPORT_SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    llm = get_reports_llm()
    try:
        response = llm.invoke(messages)
        summary_text = response.content.strip()

        # 3. Save report in DB
        last_report = db.query(Report).order_by(Report.report_id.desc()).first()
        next_id_num = 1
        if last_report and last_report.report_id.startswith("R"):
            try:
                next_id_num = int(last_report.report_id[1:]) + 1
            except ValueError:
                pass
        report_id = f"R{next_id_num:04d}"

        new_report = Report(
            report_id=report_id,
            report_type=payload.report_type,
            generated_by=officer.badge_number,
            report_date=datetime.now().strftime("%Y-%m-%d"),
            cases_covered=cases_covered,
            summary=summary_text,
        )

        db.add(new_report)
        db.commit()
        db.refresh(new_report)

        return new_report
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to generate report: {str(e)}")
