import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import settings

def send_otp_email(to_email: str, officer_name: str, otp_code: str, badge_number: str = "N/A", station: str = "N/A", rank: str = "N/A", state: str = "N/A", district: str = "N/A"):
    """Sends registration/verification OTP to the officer's email with profile details."""
    subject = "AI Intelligent Police Assistant - OTP Verification"
    
    state_name = state if state and state != "N/A" else "LPU"
    
    plain_body = f"""Dear Sir/Madam,

This is to inform you that a request has been received for identity verification on the **AI Intelligent Police Assistant Portal**.

Please use the following **One-Time Password (OTP)** to complete the verification process:

**OTP:** **[{otp_code}]**

The above OTP is valid for **10 minutes** from the time of issuance and can be used only once.

**Important Security Instructions:**

* Do not share this OTP with anyone under any circumstances.
* Government officials, system administrators, or support personnel will **never** ask for your OTP.
* If you did not initiate this request, please disregard this email. No action will be taken unless the OTP is successfully verified.

This is an automated communication generated by the **AI Intelligent Police Assistant Portal**. Please do not reply to this email.

For technical assistance, please contact the Portal Help Desk.

Regards,

**System Administrator**
**AI Intelligent Police Assistant Portal**
**Police Department, Government of {state_name}
Official Digital Services Division**"""

    html_body = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{subject}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f4f6f8;
            color: #333333;
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
        }}
        .container {{
            max-width: 600px;
            margin: 40px auto;
            background-color: #ffffff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
            border: 1px solid #e1e4e8;
        }}
        .header {{
            background-color: #1a365d;
            padding: 24px;
            text-align: center;
            color: #ffffff;
        }}
        .header h1 {{
            margin: 0;
            font-size: 20px;
            font-weight: 600;
            letter-spacing: 0.5px;
        }}
        .content {{
            padding: 32px 24px;
            line-height: 1.6;
        }}
        .greeting {{
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 16px;
        }}
        .otp-container {{
            background-color: #f7fafc;
            border: 1px dashed #cbd5e0;
            border-radius: 6px;
            padding: 20px;
            text-align: center;
            margin: 24px 0;
        }}
        .otp-label {{
            font-size: 14px;
            color: #4a5568;
            margin-bottom: 8px;
            font-weight: 500;
        }}
        .otp-code {{
            font-size: 32px;
            font-weight: 800;
            color: #2b6cb0;
            letter-spacing: 4px;
            margin: 0;
        }}
        .expiry-text {{
            font-size: 13px;
            color: #718096;
            margin-top: 8px;
        }}
        .security-box {{
            background-color: #fffaf0;
            border-left: 4px solid #dd6b20;
            padding: 16px;
            border-radius: 4px;
            margin: 24px 0;
        }}
        .security-title {{
            font-size: 14px;
            font-weight: bold;
            color: #dd6b20;
            margin-bottom: 8px;
        }}
        .security-list {{
            margin: 0;
            padding-left: 20px;
            font-size: 13px;
            color: #4a5568;
        }}
        .security-list li {{
            margin-bottom: 6px;
        }}
        .footer {{
            background-color: #f7fafc;
            padding: 24px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #718096;
            line-height: 1.5;
        }}
        .signature {{
            margin-top: 16px;
            border-top: 1px solid #e2e8f0;
            padding-top: 16px;
        }}
        .signature-title {{
            font-weight: bold;
            color: #2d3748;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AI Intelligent Police Assistant</h1>
        </div>
        <div class="content">
            <div class="greeting">Dear Sir/Madam,</div>
            <p>This is to inform you that a request has been received for identity verification on the <strong>AI Intelligent Police Assistant Portal</strong>.</p>
            <p>Please use the following <strong>One-Time Password (OTP)</strong> to complete the verification process:</p>
            
            <div class="otp-container">
                <div class="otp-label">One-Time Password (OTP)</div>
                <div class="otp-code">{otp_code}</div>
                <div class="expiry-text">The above OTP is valid for <strong>10 minutes</strong> from the time of issuance and can be used only once.</div>
            </div>

            <div class="security-box">
                <div class="security-title">⚠️ Important Security Instructions</div>
                <ul class="security-list">
                    <li>Do not share this OTP with anyone under any circumstances.</li>
                    <li>Government officials, system administrators, or support personnel will <strong>never</strong> ask for your OTP.</li>
                    <li>If you did not initiate this request, please disregard this email. No action will be taken unless the OTP is successfully verified.</li>
                </ul>
            </div>

            <p style="font-size: 13px; color: #718096; margin-top: 24px;">This is an automated communication generated by the <strong>AI Intelligent Police Assistant Portal</strong>. Please do not reply to this email.</p>
            <p style="font-size: 13px; color: #718096;">For technical assistance, please contact the Portal Help Desk.</p>
        </div>
        <div class="footer">
            <div class="signature">
                <div class="signature-title">Regards,</div>
                <p style="margin-top: 4px; font-weight: 600; color: #4a5568;">System Administrator<br>
                AI Intelligent Police Assistant Portal<br>
                Police Department, Government of {state_name}<br>
                Official Digital Services Division</p>
            </div>
        </div>
    </div>
</body>
</html>"""
    
    # Check if SMTP is configured
    if not settings.EMAIL_USERNAME or not settings.EMAIL_PASSWORD:
        print(f"\n==========================================")
        print(f"SMTP NOT CONFIGURED. PRINTING EMAIL TO CONSOLE:")
        print(f"To: {to_email}")
        print(f"Subject: {subject}")
        try:
            print(f"Body:\n{plain_body}")
        except Exception:
            import sys
            enc = sys.stdout.encoding or 'utf-8'
            print(f"Body:\n{plain_body.encode(enc, errors='replace').decode(enc)}")
        print(f"==========================================\n")
        return True

    try:
        msg = MIMEMultipart('alternative')
        msg['From'] = settings.EMAIL_USERNAME
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(plain_body, 'plain'))
        msg.attach(MIMEText(html_body, 'html'))
        
        # Determine whether to use SSL or TLS
        if settings.MAIL_SSL:
            server = smtplib.SMTP_SSL(settings.MAIL_SERVER, settings.MAIL_PORT)
        else:
            server = smtplib.SMTP(settings.MAIL_SERVER, settings.MAIL_PORT)
            if settings.MAIL_TLS:
                server.starttls()
        
        server.login(settings.EMAIL_USERNAME, settings.EMAIL_PASSWORD)
        server.sendmail(settings.EMAIL_USERNAME, to_email, msg.as_string())
        server.quit()
        print(f"OTP Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send OTP email: {e}")
        return False


def send_activation_email(to_email: str, officer_name: str, badge_id: str, rank: str, station: str, role: str, district: str = "N/A", state: str = "N/A", date_of_joining: str = None, temporary_password: str = "********"):
    """Sends account activation congratulations email upon successful OTP verification."""
    subject = "AI Intelligent Police Assistant (ICIP) - Onboarding & Access Credentials"
    
    from datetime import datetime
    if not date_of_joining:
        date_of_joining = datetime.now().strftime("%d %b %Y")
        
    state_display = state if state and state != "N/A" else "LPU"
    department = "Law Enforcement & Digital Policing Division"
    
    plain_body = f"""Dear **{officer_name}**,

Congratulations and welcome to the **AI Intelligent Police Assistant (ICIP)** platform.

We are delighted to have you join our digital law enforcement ecosystem. Your account has been successfully created, and you are now authorized to access the ICIP portal.

**Employee Details**

* **Officer Name:** {officer_name}
* **Badge ID:** {badge_id}
* **Rank:** {rank}
* **Police Station:** {station}
* **Department:** {department}
* **Official Email:** {to_email}
* **Joining Date:** {date_of_joining}

**Portal Access**

* **Portal URL:** https://icip.gov.in
* **Username:** {badge_id}
* **Temporary Password:** {temporary_password}

For security reasons, you will be required to change your password during your first login and enable Multi-Factor Authentication (MFA).

### Your ICIP Access Includes

* AI Police Assistant
* FIR Draft Generation
* Complaint Registration & Tracking
* Criminal Record Search
* Case Management Dashboard
* Evidence Management
* Incident Analytics
* Secure Internal Communication

### Documents Required

Please ensure the following documents are uploaded to complete your onboarding:

* Government Identity Card
* Police Department ID
* Appointment/Posting Order
* Passport-size Photograph

### Important Security Guidelines

* Do not share your login credentials.
* Always log out after completing your work.
* Report any suspicious activity immediately to the System Administrator.
* Access to ICIP is monitored and protected under departmental cybersecurity policies.

If you experience any issues while accessing the platform, please contact:

**ICIP Technical Support**
Email: support@icip.gov.in
Phone: +91-XXXXXXXXXX

We are committed to providing you with a secure, intelligent, and efficient policing experience.

Once again, welcome to the **AI Intelligent Police Assistant (ICIP)**.

We wish you success in your service.

Regards,

**Human Resources Division**
**AI Intelligent Police Assistant (ICIP)**
Government Digital Policing Initiative

*This is a system-generated email. Please do not reply to this message.*"""

    html_body = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{subject}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: #f8fafc;
            color: #1e293b;
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
        }}
        .container {{
            max-width: 600px;
            margin: 40px auto;
            background-color: #ffffff;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
            border: 1px solid #e2e8f0;
        }}
        .header {{
            background: linear-gradient(135deg, #1e3a8a 0%, #0f172a 100%);
            padding: 32px 24px;
            text-align: center;
            color: #ffffff;
            border-bottom: 4px solid #d97706;
        }}
        .header h1 {{
            margin: 0;
            font-size: 22px;
            font-weight: 700;
            letter-spacing: 0.5px;
            text-transform: uppercase;
            color: #ffffff;
        }}
        .content {{
            padding: 32px 24px;
            line-height: 1.6;
        }}
        .greeting {{
            font-size: 18px;
            font-weight: 700;
            color: #0f172a;
            margin-bottom: 16px;
        }}
        .intro-text {{
            font-size: 14px;
            color: #334155;
            margin-bottom: 24px;
        }}
        .section-title {{
            font-size: 15px;
            font-weight: 700;
            color: #1e3a8a;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 28px;
            margin-bottom: 12px;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 6px;
        }}
        .details-grid {{
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 24px;
        }}
        .detail-row {{
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #edf2f7;
            font-size: 13.5px;
        }}
        .detail-row:last-child {{
            border-bottom: none;
        }}
        .detail-label {{
            font-weight: 600;
            color: #475569;
            width: 40%;
        }}
        .detail-value {{
            color: #0f172a;
            font-weight: 500;
            width: 60%;
            text-align: right;
        }}
        .access-box {{
            background-color: #fffbeb;
            border: 1px solid #fef3c7;
            border-left: 4px solid #d97706;
            border-radius: 6px;
            padding: 18px;
            margin-bottom: 24px;
        }}
        .access-row {{
            display: flex;
            justify-content: space-between;
            padding: 6px 0;
            font-size: 13.5px;
            align-items: center;
        }}
        .access-label {{
            font-weight: 700;
            color: #b45309;
        }}
        .access-value {{
            font-family: monospace;
            font-weight: bold;
            color: #78350f;
            background-color: #fde68a;
            padding: 2px 6px;
            border-radius: 4px;
        }}
        .access-url {{
            color: #2563eb;
            text-decoration: underline;
            font-weight: 600;
        }}
        .security-note {{
            font-size: 12px;
            color: #64748b;
            font-style: italic;
            margin-top: 8px;
            border-top: 1px solid #fde68a;
            padding-top: 8px;
        }}
        .bullets-list {{
            margin: 0;
            padding-left: 20px;
            font-size: 13.5px;
            color: #334155;
        }}
        .bullets-list li {{
            margin-bottom: 8px;
        }}
        .support-box {{
            background-color: #f1f5f9;
            border-radius: 8px;
            padding: 16px;
            margin-top: 24px;
            font-size: 13px;
            color: #475569;
        }}
        .support-title {{
            font-weight: 700;
            color: #0f172a;
            margin-bottom: 6px;
        }}
        .support-link {{
            color: #2563eb;
            text-decoration: none;
            font-weight: 600;
        }}
        .footer {{
            background-color: #f1f5f9;
            padding: 24px;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #64748b;
            text-align: center;
        }}
        .signature-section {{
            text-align: left;
            margin-top: 24px;
            font-size: 13.5px;
            color: #334155;
        }}
        .signature-title {{
            font-weight: 700;
            color: #0f172a;
        }}
        .system-generated {{
            margin-top: 16px;
            font-size: 11px;
            color: #94a3b8;
            font-style: italic;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AI Intelligent Police Assistant</h1>
        </div>
        <div class="content">
            <div class="greeting">Dear <strong>{officer_name}</strong>,</div>
            <p class="intro-text">Congratulations and welcome to the <strong>AI Intelligent Police Assistant (ICIP)</strong> platform.<br><br>
            We are delighted to have you join our digital law enforcement ecosystem. Your account has been successfully created, and you are now authorized to access the ICIP portal.</p>
            
            <div class="section-title">Employee Details</div>
            <div class="details-grid">
                <div class="detail-row">
                    <span class="detail-label">Officer Name:</span>
                    <span class="detail-value">{officer_name}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Badge ID:</span>
                    <span class="detail-value">{badge_id}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Rank:</span>
                    <span class="detail-value">{rank}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Police Station:</span>
                    <span class="detail-value">{station}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Department:</span>
                    <span class="detail-value">{department}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Official Email:</span>
                    <span class="detail-value">{to_email}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Joining Date:</span>
                    <span class="detail-value">{date_of_joining}</span>
                </div>
            </div>

            <div class="section-title">Portal Access</div>
            <div class="access-box">
                <div class="access-row" style="border-bottom: 1px solid #fde68a; padding-bottom: 6px; margin-bottom: 6px;">
                    <span class="access-label">Portal URL:</span>
                    <span><a href="https://icip.gov.in" class="access-url" target="_blank">https://icip.gov.in</a></span>
                </div>
                <div class="access-row">
                    <span class="access-label">Username:</span>
                    <span class="access-value">{badge_id}</span>
                </div>
                <div class="access-row">
                    <span class="access-label">Temporary Password:</span>
                    <span class="access-value">{temporary_password}</span>
                </div>
                <div class="security-note">
                    For security reasons, you will be required to change your password during your first login and enable Multi-Factor Authentication (MFA).
                </div>
            </div>

            <div class="section-title">Your ICIP Access Includes</div>
            <ul class="bullets-list">
                <li>AI Police Assistant</li>
                <li>FIR Draft Generation</li>
                <li>Complaint Registration & Tracking</li>
                <li>Criminal Record Search</li>
                <li>Case Management Dashboard</li>
                <li>Evidence Management</li>
                <li>Incident Analytics</li>
                <li>Secure Internal Communication</li>
            </ul>

            <div class="section-title">Documents Required</div>
            <p class="intro-text" style="margin-bottom: 8px;">Please ensure the following documents are uploaded to complete your onboarding:</p>
            <ul class="bullets-list">
                <li>Government Identity Card</li>
                <li>Police Department ID</li>
                <li>Appointment/Posting Order</li>
                <li>Passport-size Photograph</li>
            </ul>

            <div class="section-title">Important Security Guidelines</div>
            <ul class="bullets-list">
                <li>Do not share your login credentials.</li>
                <li>Always log out after completing your work.</li>
                <li>Report any suspicious activity immediately to the System Administrator.</li>
                <li>Access to ICIP is monitored and protected under departmental cybersecurity policies.</li>
            </ul>

            <div class="support-box">
                <div class="support-title">ICIP Technical Support</div>
                Email: <a href="mailto:support@icip.gov.in" class="support-link">support@icip.gov.in</a><br>
                Phone: +91-XXXXXXXXXX
            </div>

            <p class="intro-text" style="margin-top: 24px; font-weight: 500;">
                We are committed to providing you with a secure, intelligent, and efficient policing experience.<br><br>
                Once again, welcome to the <strong>AI Intelligent Police Assistant (ICIP)</strong>.<br><br>
                We wish you success in your service.
            </p>

            <div class="signature-section">
                Regards,<br><br>
                <span class="signature-title">Human Resources Division</span><br>
                <strong>AI Intelligent Police Assistant (ICIP)</strong><br>
                Government Digital Policing Initiative
            </div>
            
            <div class="system-generated">
                *This is a system-generated email. Please do not reply to this message.*
            </div>
        </div>
        <div class="footer">
            &copy; {datetime.now().year} AI Intelligent Police Assistant (ICIP). All rights reserved.
        </div>
    </div>
</body>
</html>"""

    # Check if SMTP is configured
    if not settings.EMAIL_USERNAME or not settings.EMAIL_PASSWORD:
        print(f"\n==========================================")
        print(f"SMTP NOT CONFIGURED. PRINTING EMAIL TO CONSOLE:")
        print(f"To: {to_email}")
        print(f"Subject: {subject}")
        try:
            print(f"Body:\n{plain_body}")
        except Exception:
            import sys
            enc = sys.stdout.encoding or 'utf-8'
            print(f"Body:\n{plain_body.encode(enc, errors='replace').decode(enc)}")
        print(f"==========================================\n")
        return True

    try:
        msg = MIMEMultipart('alternative')
        msg['From'] = settings.EMAIL_USERNAME
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(plain_body, 'plain'))
        msg.attach(MIMEText(html_body, 'html'))
        
        # Determine whether to use SSL or TLS
        if settings.MAIL_SSL:
            server = smtplib.SMTP_SSL(settings.MAIL_SERVER, settings.MAIL_PORT)
        else:
            server = smtplib.SMTP(settings.MAIL_SERVER, settings.MAIL_PORT)
            if settings.MAIL_TLS:
                server.starttls()
        
        server.login(settings.EMAIL_USERNAME, settings.EMAIL_PASSWORD)
        server.sendmail(settings.EMAIL_USERNAME, to_email, msg.as_string())
        server.quit()
        print(f"Activation Congratulations Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send activation email: {e}")
        return False
